# Generated by Django 2.2 on 2020-12-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=2000)),
                ('a', models.CharField(max_length=2000)),
                ('b', models.CharField(max_length=2000)),
                ('c', models.CharField(max_length=2000)),
                ('d', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
                ('think', models.CharField(max_length=2000)),
            ],
        ),
    ]
